### PR TITLE
Function to download datasets directly from DXC public github 

### PR DESCRIPTION
**Pull request by Amarify**
Reason to implement

1. Give user flexibility to download only required datasets directly from DXC public GitHub.
2. Reduce the size of AI starter library by moving all pre-configured datasets to DXC AI starter public GitHub.

### CODE REVIEW

**Comment by madhubandru** [comment]
Hi @Amarify,

Can you please share the test results for the changes made?

Thank you

**Review by madhubandru — APPROVED** [review]
Hi,

Proposed changes are tested and good to merge to master.

**Review by npulagam — COMMENTED** [review]
Changes are good to merge with the master branch.

**Review by npulagam — COMMENTED** [review]
Changes are good to merge with the master branch.

**Pull request merged**
